dbConfig:
    dbConfigFile: /home/manuelpadilla/source/reposUbuntu/CARDANO/cardano-tools-scripts-v1.0/files/pab/plutus-pab.StakePlusV2.db
    dbConfigPoolSize: 20

pabWebserverConfig:
  baseUrl: http://localhost:9080
  staticDir: plutus-pab-client/dist
  permissiveCorsPolicy: False
  # Optional timeout (in seconds) for calls to endpoints that are not currently
  # available. If this is not set, calls to unavailable endpoints fail
  # immediately.
  endpointTimeout: 20
  enableMarconi: False

walletServerConfig:
  tag: LocalWalletConfig
  walletSettings:
    baseUrl: http://localhost:9091

nodeServerConfig:
  pscBaseUrl: http://localhost:3001
  pscSocketPath: /home/manuelpadilla/source/tools/cardano-node-1.35.3-linux/db-testnet-preview/node.socket
  pscKeptBlocks: 100
  pscNetworkId: "2" # Testnet network ID (main net = empty string)
  pscSlotConfig:
    scSlotZeroTime: 1596059091000 # Wednesday, July 29, 2020 21:44:51 - shelley launch time in milliseconds
    scSlotLength: 1000 # In milliseconds
  pscFeeConfig:
    fcConstantFee:
      getLovelace: 10 # Constant fee per transaction in lovelace
    fcScriptsFeeFactor: 1.0 # Factor by which to multiply size-dependent scripts fee in lovelace
  pscInitialTxWallets: []
  pscNodeMode: AlonzoNode
  #pscInitialTxWallets:
  #  - getWallet: 1
  #  - getWallet: 2
  #  - getWallet: 3
  #pscNodeMode: MockNode

chainIndexConfig:
  ciBaseUrl: http://localhost:9083

requestProcessingConfig:
  requestProcessingInterval: 1

signingProcessConfig:
  spBaseUrl: http://localhost:9084
  spWallet:
    getWallet: 1

metadataServerConfig:
  mdBaseUrl: http://localhost:9085

developmentOptions:
  pabRollbackHistory: null
  pabResumeFrom:
    #{ "tag" : "PointAtGenesis" }
    { "tag" : "Point"
    , "pointBlockId" : "e94726c3c1d48630fa950b01ab6065405afad46ebf35f8523b08581be000a951"
    , "pointSlot" : { "getSlot" : 2925973 }
    }

# Optional EKG Server Config
# ----
# monitoringConfig:
#   monitoringPort: 9090
